"""
CATERYA Export Manager — Convert agent results to PDF, Excel, JSON, CSV, Markdown, TXT
Author: Ary HH (Caterya Tech) <aryhharyanto@proton.me>

Works fully offline. No cloud dependencies.
All exports done in-memory and returned as bytes for Streamlit download buttons.
"""

from __future__ import annotations

import csv
import io
import json
import re
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any


# ─── Data Model ──────────────────────────────────────────────────────────────

@dataclass
class ExportPayload:
    """Unified payload for all export formats."""
    title: str = ""
    agent_id: str = "agent"
    task: str = ""
    content: str = ""                    # main output / result
    metadata: dict = field(default_factory=dict)
    ethics_verdict: str = "pass"
    duration_ms: float = 0
    steps: list[dict] = field(default_factory=list)  # pipeline steps
    timestamp: str = field(default_factory=lambda: _now_str())
    success: bool = True

    @classmethod
    def from_result(cls, result: dict, task: str = "", title: str = "") -> "ExportPayload":
        """Build ExportPayload from agent run_agent() result dict."""
        return cls(
            title=title or f"{result.get('agent_id','agent').replace('_',' ').title()} — {task[:50]}",
            agent_id=result.get("agent_id", "agent"),
            task=task or result.get("task", ""),
            content=result.get("result", "") or result.get("final_output", ""),
            metadata=result.get("metadata", {}),
            ethics_verdict=result.get("ethics_verdict", "pass"),
            duration_ms=result.get("duration_ms", 0),
            steps=result.get("steps", []),
            success=result.get("success", True),
        )


# ─── Helpers ─────────────────────────────────────────────────────────────────

def _now_str() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

def _slug(text: str) -> str:
    """Make filesystem-safe filename slug."""
    return re.sub(r"[^\w\-]", "_", text[:40]).strip("_")

def _strip_md(text: str) -> str:
    """Remove markdown formatting for plain text contexts."""
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"\*(.+?)\*", r"\1", text)
    text = re.sub(r"`(.+?)`", r"\1", text)
    text = re.sub(r"^#{1,6}\s+", "", text, flags=re.MULTILINE)
    text = re.sub(r"^\s*[-*+]\s+", "• ", text, flags=re.MULTILINE)
    return text.strip()


# ─── JSON Export ─────────────────────────────────────────────────────────────

def export_json(result: dict, pretty: bool = True) -> bytes:
    """Export agent result as JSON."""
    payload = {
        "caterya_export": True,
        "exported_at": _now_str(),
        "version": "1.0",
        "data": result,
    }
    indent = 2 if pretty else None
    return json.dumps(payload, indent=indent, ensure_ascii=False, default=str).encode("utf-8")


# ─── Markdown Export ─────────────────────────────────────────────────────────

def export_markdown(result: dict, title: str = "") -> bytes:
    """Export agent result as Markdown report."""
    agent_id = result.get("agent_id", "agent")
    task = result.get("task", "")
    output = result.get("result", "")
    ethics = result.get("ethics_verdict", "pass").upper()
    ts = result.get("timestamp", _now_str())
    duration = result.get("duration_ms", 0)

    lines = [
        f"# CATERYA Report — {title or agent_id.replace('_', ' ').title()}",
        "",
        f"> Generated by CATERYA Agentic Enterprise | {ts}",
        "",
        "---",
        "",
        "## Task",
        "",
        task,
        "",
        "---",
        "",
        "## Output",
        "",
        output,
        "",
        "---",
        "",
        "## Metadata",
        "",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| Agent | `{agent_id}` |",
        f"| Ethics Verdict | `{ethics}` |",
        f"| Duration | {duration:.0f}ms |",
        f"| Exported | {_now_str()} |",
        "",
        "---",
        "",
        "*© 2026 Caterya Tech — Confidential*",
    ]

    # Add pipeline steps if present
    steps = result.get("steps", [])
    if steps:
        lines.insert(-3, "## Pipeline Steps")
        lines.insert(-3, "")
        for i, step in enumerate(steps, 1):
            lines.insert(-3, f"### Step {i}: {step.get('agent', '').replace('_', ' ').title()}")
            lines.insert(-3, "")
            lines.insert(-3, step.get("output", ""))
            lines.insert(-3, "")

    return "\n".join(lines).encode("utf-8")


# ─── CSV Export ──────────────────────────────────────────────────────────────

def export_csv(result: dict) -> bytes:
    """Export agent result as CSV (flat key-value + steps if pipeline)."""
    buf = io.StringIO()
    writer = csv.writer(buf)

    steps = result.get("steps", [])

    if steps:
        # Pipeline: one row per step
        writer.writerow(["step", "agent", "task", "output", "ethics_verdict", "duration_ms"])
        for i, step in enumerate(steps, 1):
            writer.writerow([
                i,
                step.get("agent", ""),
                step.get("task", ""),
                step.get("output", "")[:500],  # truncate for CSV
                step.get("ethics_verdict", ""),
                step.get("duration_ms", ""),
            ])
        # Summary row
        writer.writerow([])
        writer.writerow(["SUMMARY", "", "", "", "", ""])
        writer.writerow(["final_output", "", "", result.get("final_output", result.get("result", ""))[:500], "", ""])
    else:
        # Single agent: key-value pairs
        writer.writerow(["field", "value"])
        flat_fields = [
            ("agent_id", result.get("agent_id", "")),
            ("task", result.get("task", "")),
            ("result", result.get("result", "")[:1000]),
            ("ethics_verdict", result.get("ethics_verdict", "")),
            ("duration_ms", result.get("duration_ms", "")),
            ("success", result.get("success", "")),
            ("exported_at", _now_str()),
        ]
        for k, v in flat_fields:
            writer.writerow([k, str(v)])

        # Metadata section
        meta = result.get("metadata", {})
        if meta:
            writer.writerow([])
            writer.writerow(["--- METADATA ---", ""])
            for k, v in meta.items():
                writer.writerow([k, str(v)])

    return buf.getvalue().encode("utf-8")


# ─── Excel Export ────────────────────────────────────────────────────────────

def export_excel(result: dict, title: str = "") -> bytes:
    """
    Export agent result as Excel (.xlsx) with:
    - Sheet 1: Summary (title, task, output, metadata)
    - Sheet 2: Pipeline steps (if multi-agent run)
    - Sheet 3: Raw JSON
    Uses openpyxl — no LibreOffice needed, pure Python, works on Streamlit Cloud.
    """
    try:
        import openpyxl
        from openpyxl.styles import (
            Font, PatternFill, Alignment, Border, Side, GradientFill
        )
        from openpyxl.utils import get_column_letter
    except ImportError:
        raise ImportError("openpyxl required: pip install openpyxl")

    wb = openpyxl.Workbook()

    # ── Colors ────────────────────────────────────────────────────────────────
    TEAL       = "FF00D4AA"
    DARK_BG    = "FF0F0F1A"
    DARK_CARD  = "FF1A1A2E"
    WHITE      = "FFFFFFFF"
    GRAY       = "FF888888"
    LIGHT_GRAY = "FFF5F5F5"
    ORANGE     = "FFFF6B00"
    GREEN      = "FF22C55E"
    RED        = "FFE53E3E"

    def h1(ws, row, col, text):
        c = ws.cell(row=row, column=col, value=text)
        c.font = Font(name="Arial", bold=True, size=16, color=TEAL)
        c.alignment = Alignment(horizontal="left", vertical="center")
        return c

    def h2(ws, row, col, text):
        c = ws.cell(row=row, column=col, value=text)
        c.font = Font(name="Arial", bold=True, size=12, color="FF333333")
        c.fill = PatternFill("solid", fgColor=LIGHT_GRAY)
        c.alignment = Alignment(horizontal="left", vertical="center")
        return c

    def label(ws, row, col, text):
        c = ws.cell(row=row, column=col, value=text)
        c.font = Font(name="Arial", bold=True, size=10, color="FF555555")
        c.alignment = Alignment(horizontal="left", vertical="top", wrap_text=True)
        return c

    def value_cell(ws, row, col, text, wrap=True):
        c = ws.cell(row=row, column=col, value=str(text) if text is not None else "")
        c.font = Font(name="Arial", size=10, color="FF111111")
        c.alignment = Alignment(horizontal="left", vertical="top", wrap_text=wrap)
        return c

    def verdict_cell(ws, row, col, verdict):
        c = ws.cell(row=row, column=col, value=verdict.upper())
        color = {"PASS": GREEN, "WARN": ORANGE, "BLOCK": RED, "ERROR": RED}.get(verdict.upper(), GRAY)
        c.font = Font(name="Arial", bold=True, size=10, color=color)
        c.alignment = Alignment(horizontal="center", vertical="center")
        return c

    def thin_border():
        side = Side(style="thin", color="FFDDDDDD")
        return Border(left=side, right=side, top=side, bottom=side)

    agent_id = result.get("agent_id", "agent")
    task = result.get("task", "")
    output = result.get("result", "") or result.get("final_output", "")
    ethics = result.get("ethics_verdict", "pass")
    duration = result.get("duration_ms", 0)
    steps = result.get("steps", [])
    meta = result.get("metadata", {})
    report_title = title or f"CATERYA Report — {agent_id.replace('_', ' ').title()}"

    # ── Sheet 1: Summary ──────────────────────────────────────────────────────
    ws1 = wb.active
    ws1.title = "Summary"
    ws1.sheet_view.showGridLines = False
    ws1.column_dimensions["A"].width = 22
    ws1.column_dimensions["B"].width = 85
    ws1.row_dimensions[1].height = 40
    ws1.row_dimensions[2].height = 20

    # Header bar
    ws1.merge_cells("A1:B1")
    title_cell = ws1["A1"]
    title_cell.value = f"⚡ {report_title}"
    title_cell.font = Font(name="Arial", bold=True, size=18, color=WHITE)
    title_cell.fill = PatternFill("solid", fgColor=DARK_BG)
    title_cell.alignment = Alignment(horizontal="left", vertical="center", indent=1)

    ws1.merge_cells("A2:B2")
    sub = ws1["A2"]
    sub.value = f"CATERYA Agentic Enterprise  ·  Generated: {_now_str()}  ·  Agent: {agent_id}"
    sub.font = Font(name="Arial", size=9, color=GRAY)
    sub.fill = PatternFill("solid", fgColor=DARK_CARD)
    sub.alignment = Alignment(horizontal="left", vertical="center", indent=1)

    row = 4
    h2(ws1, row, 1, "📋 Task / Prompt")
    ws1.merge_cells(f"A{row}:B{row}")
    ws1.row_dimensions[row].height = 20
    row += 1

    ws1.merge_cells(f"A{row}:B{row}")
    tc = value_cell(ws1, row, 1, task)
    ws1.row_dimensions[row].height = max(40, min(120, len(task) // 2))
    row += 2

    h2(ws1, row, 1, "📄 Output / Result")
    ws1.merge_cells(f"A{row}:B{row}")
    ws1.row_dimensions[row].height = 20
    row += 1

    ws1.merge_cells(f"A{row}:B{row}")
    oc = value_cell(ws1, row, 1, _strip_md(output))
    ws1.row_dimensions[row].height = max(80, min(400, len(output) // 3))
    row += 2

    h2(ws1, row, 1, "ℹ️ Details")
    ws1.merge_cells(f"A{row}:B{row}")
    row += 1

    details = [
        ("Agent", agent_id),
        ("Ethics Verdict", ethics.upper()),
        ("Duration", f"{duration:.0f} ms"),
        ("Success", "Yes" if result.get("success") else "No"),
        ("Exported At", _now_str()),
    ]
    for k, v in details:
        label(ws1, row, 1, k)
        if k == "Ethics Verdict":
            verdict_cell(ws1, row, 2, v)
        else:
            value_cell(ws1, row, 2, v, wrap=False)
        ws1.row_dimensions[row].height = 18
        row += 1

    if meta:
        row += 1
        h2(ws1, row, 1, "🔍 Metadata")
        ws1.merge_cells(f"A{row}:B{row}")
        row += 1
        for k, v in meta.items():
            label(ws1, row, 1, str(k))
            value_cell(ws1, row, 2, str(v))
            ws1.row_dimensions[row].height = 18
            row += 1

    # ── Sheet 2: Pipeline Steps (if multi-agent) ──────────────────────────────
    if steps:
        ws2 = wb.create_sheet("Pipeline Steps")
        ws2.sheet_view.showGridLines = False
        ws2.column_dimensions["A"].width = 8
        ws2.column_dimensions["B"].width = 22
        ws2.column_dimensions["C"].width = 35
        ws2.column_dimensions["D"].width = 70
        ws2.column_dimensions["E"].width = 14
        ws2.column_dimensions["F"].width = 14

        ws2.merge_cells("A1:F1")
        t = ws2["A1"]
        t.value = f"⚡ CATERYA — Pipeline Steps  ·  {report_title}"
        t.font = Font(name="Arial", bold=True, size=14, color=WHITE)
        t.fill = PatternFill("solid", fgColor=DARK_BG)
        t.alignment = Alignment(horizontal="left", vertical="center", indent=1)
        ws2.row_dimensions[1].height = 36

        headers = ["#", "Agent", "Task", "Output", "Ethics", "Duration (ms)"]
        for col_i, hdr in enumerate(headers, 1):
            c = ws2.cell(row=2, column=col_i, value=hdr)
            c.font = Font(name="Arial", bold=True, size=10, color=WHITE)
            c.fill = PatternFill("solid", fgColor="FF2D2D44")
            c.alignment = Alignment(horizontal="center", vertical="center")
            c.border = thin_border()

        for i, step in enumerate(steps, 1):
            row_i = i + 2
            step_output = step.get("output", "") or step.get("result", "")
            cells_data = [
                (i, False),
                (step.get("agent", "").replace("_", " ").title(), False),
                (step.get("task", "")[:200], True),
                (_strip_md(step_output)[:800], True),
                (step.get("ethics_verdict", "pass").upper(), False),
                (step.get("duration_ms", ""), False),
            ]
            fill_color = "FFFAFAFA" if i % 2 == 0 else WHITE
            for col_i, (val, wrap) in enumerate(cells_data, 1):
                c = ws2.cell(row=row_i, column=col_i, value=str(val) if val is not None else "")
                c.font = Font(name="Arial", size=9)
                c.alignment = Alignment(horizontal="left", vertical="top", wrap_text=wrap)
                c.fill = PatternFill("solid", fgColor=fill_color)
                c.border = thin_border()
                if col_i == 5:  # ethics
                    verdict_cell(ws2, row_i, col_i, str(val))
            ws2.row_dimensions[row_i].height = max(40, min(120, len(str(step_output)) // 8))

    # ── Sheet 3: Raw JSON ─────────────────────────────────────────────────────
    ws3 = wb.create_sheet("Raw JSON")
    ws3.sheet_view.showGridLines = False
    ws3.column_dimensions["A"].width = 110

    ws3["A1"].value = "Raw JSON Export"
    ws3["A1"].font = Font(name="Courier New", bold=True, size=11, color=TEAL)

    raw_json = json.dumps(result, indent=2, ensure_ascii=False, default=str)
    for i, line in enumerate(raw_json.split("\n"), 2):
        c = ws3.cell(row=i, column=1, value=line)
        c.font = Font(name="Courier New", size=9, color="FF333333")

    # ── Save ──────────────────────────────────────────────────────────────────
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


# ─── PDF Export ──────────────────────────────────────────────────────────────

def export_pdf(result: dict, title: str = "") -> bytes:
    """
    Export agent result as PDF using reportlab.
    Professional layout with CATERYA branding, dark header, metadata table.
    """
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import mm
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
            HRFlowable, PageBreak, KeepTogether
        )
        from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
    except ImportError:
        raise ImportError("reportlab required: pip install reportlab")

    agent_id = result.get("agent_id", "agent")
    task = result.get("task", "")
    output = result.get("result", "") or result.get("final_output", "")
    ethics = result.get("ethics_verdict", "pass").upper()
    duration = result.get("duration_ms", 0)
    steps = result.get("steps", [])
    meta = result.get("metadata", {})
    report_title = title or f"CATERYA Report — {agent_id.replace('_', ' ').title()}"

    # Colors
    TEAL_COLOR   = colors.HexColor("#00D4AA")
    DARK_COLOR   = colors.HexColor("#0F0F1A")
    CARD_COLOR   = colors.HexColor("#1A1A2E")
    GRAY_COLOR   = colors.Color(0.5, 0.5, 0.5)
    WHITE_COLOR  = colors.white
    ORANGE_COLOR = colors.HexColor("#FF6B00")
    GREEN_COLOR  = colors.HexColor("#22C55E")
    RED_COLOR    = colors.HexColor("#E53E3E")

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=20*mm,
        leftMargin=20*mm,
        topMargin=15*mm,
        bottomMargin=20*mm,
    )

    styles = getSampleStyleSheet()

    s_title = ParagraphStyle(
        "CateryaTitle",
        fontName="Helvetica-Bold",
        fontSize=20,
        textColor=TEAL_COLOR,
        spaceAfter=4,
        leading=24,
    )
    s_subtitle = ParagraphStyle(
        "CateryaSub",
        fontName="Helvetica",
        fontSize=8,
        textColor=GRAY_COLOR,
        spaceAfter=0,
    )
    s_h2 = ParagraphStyle(
        "CateryaH2",
        fontName="Helvetica-Bold",
        fontSize=12,
        textColor=DARK_COLOR,
        spaceBefore=12,
        spaceAfter=6,
        borderPad=4,
    )
    s_body = ParagraphStyle(
        "CateryaBody",
        fontName="Helvetica",
        fontSize=9,
        textColor=colors.HexColor("#333333"),
        leading=14,
        spaceAfter=4,
    )
    s_label = ParagraphStyle(
        "CateryaLabel",
        fontName="Helvetica-Bold",
        fontSize=8,
        textColor=colors.HexColor("#555555"),
    )
    s_footer = ParagraphStyle(
        "CateryaFooter",
        fontName="Helvetica",
        fontSize=7,
        textColor=GRAY_COLOR,
        alignment=TA_CENTER,
    )
    s_code = ParagraphStyle(
        "CateryaCode",
        fontName="Courier",
        fontSize=8,
        textColor=colors.HexColor("#1A1A2E"),
        backColor=colors.HexColor("#F5F5F5"),
        leading=12,
        leftIndent=8,
        rightIndent=8,
    )

    def md_to_para(text: str, style) -> list:
        """Convert markdown text to reportlab Paragraphs."""
        paras = []
        for line in text.split("\n"):
            line = line.strip()
            if not line:
                paras.append(Spacer(1, 4))
                continue
            # Headers
            if line.startswith("### "):
                p = Paragraph(line[4:], ParagraphStyle("md_h3", parent=s_label, fontSize=10, textColor=TEAL_COLOR, spaceBefore=8))
            elif line.startswith("## "):
                p = Paragraph(line[3:], ParagraphStyle("md_h2", parent=s_h2, fontSize=11))
            elif line.startswith("# "):
                p = Paragraph(line[2:], ParagraphStyle("md_h1", parent=s_h2, fontSize=13))
            elif line.startswith("• ") or line.startswith("- ") or line.startswith("* "):
                line = "• " + line[2:]
                p = Paragraph(line, ParagraphStyle("md_li", parent=style, leftIndent=12))
            else:
                # Bold
                line = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", line)
                line = re.sub(r"`(.+?)`", r'<font name="Courier" color="#1A1A2E">\1</font>', line)
                p = Paragraph(line, style)
            paras.append(p)
        return paras

    story = []

    # ── Header Block ─────────────────────────────────────────────────────────
    header_data = [[
        Paragraph(f"⚡ {report_title}", s_title),
        Paragraph(f"{_now_str()}", ParagraphStyle("ts", parent=s_subtitle, alignment=TA_RIGHT)),
    ]]
    header_table = Table(header_data, colWidths=[130*mm, 40*mm])
    header_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), DARK_COLOR),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (0, -1), 14),
        ("RIGHTPADDING", (-1, 0), (-1, -1), 14),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROUNDEDCORNERS", [6]),
    ]))
    story.append(header_table)

    # Agent + Ethics badge row
    ethics_color = {"PASS": GREEN_COLOR, "WARN": ORANGE_COLOR, "BLOCK": RED_COLOR, "ERROR": RED_COLOR}.get(ethics, GRAY_COLOR)
    badge_data = [[
        Paragraph(f"Agent: <b>{agent_id}</b>  ·  Duration: {duration:.0f}ms", ParagraphStyle("badge_l", parent=s_subtitle, textColor=GRAY_COLOR, fontSize=9)),
        Paragraph(f"Ethics: <b><font color='#{hex(ethics_color.hexval())[2:].upper()}'>{ethics}</font></b>", ParagraphStyle("badge_r", parent=s_subtitle, alignment=TA_RIGHT, fontSize=9)),
    ]]
    badge_table = Table(badge_data, colWidths=[130*mm, 40*mm])
    badge_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), CARD_COLOR),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (0, -1), 14),
        ("RIGHTPADDING", (-1, 0), (-1, -1), 14),
    ]))
    story.append(badge_table)
    story.append(Spacer(1, 10))

    # ── Task ──────────────────────────────────────────────────────────────────
    story.append(Paragraph("Task / Prompt", s_h2))
    story.append(HRFlowable(width="100%", thickness=1, color=TEAL_COLOR))
    story.append(Spacer(1, 4))
    story.append(Paragraph(task, s_body))
    story.append(Spacer(1, 10))

    # ── Output ────────────────────────────────────────────────────────────────
    story.append(Paragraph("Output", s_h2))
    story.append(HRFlowable(width="100%", thickness=1, color=TEAL_COLOR))
    story.append(Spacer(1, 4))
    story.extend(md_to_para(output, s_body))
    story.append(Spacer(1, 10))

    # ── Pipeline Steps ────────────────────────────────────────────────────────
    if steps:
        story.append(PageBreak())
        story.append(Paragraph("Pipeline Steps", s_h2))
        story.append(HRFlowable(width="100%", thickness=1, color=TEAL_COLOR))
        story.append(Spacer(1, 8))

        for i, step in enumerate(steps, 1):
            step_agent = step.get("agent", "").replace("_", " ").title()
            step_output = step.get("output", "") or step.get("result", "")
            step_ethics = step.get("ethics_verdict", "pass").upper()

            step_header = Table([[
                Paragraph(f"Step {i}: {step_agent}", ParagraphStyle("sh", parent=s_body, fontName="Helvetica-Bold", textColor=TEAL_COLOR)),
                Paragraph(f"Ethics: {step_ethics}", ParagraphStyle("se", parent=s_body, alignment=TA_RIGHT, fontSize=8, textColor=GRAY_COLOR)),
            ]], colWidths=[130*mm, 40*mm])
            step_header.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F0FDFB")),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("LEFTPADDING", (0, 0), (0, -1), 8),
                ("BOX", (0, 0), (-1, -1), 0.5, TEAL_COLOR),
            ]))
            story.append(KeepTogether([step_header]))
            story.append(Spacer(1, 4))
            story.extend(md_to_para(step_output, s_body))
            story.append(Spacer(1, 8))
            story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#EEEEEE")))
            story.append(Spacer(1, 4))

    # ── Metadata ──────────────────────────────────────────────────────────────
    if meta:
        story.append(Spacer(1, 6))
        story.append(Paragraph("Metadata", s_h2))
        story.append(HRFlowable(width="100%", thickness=1, color=TEAL_COLOR))
        meta_rows = [[Paragraph("<b>Key</b>", s_label), Paragraph("<b>Value</b>", s_label)]]
        for k, v in meta.items():
            meta_rows.append([
                Paragraph(str(k), s_label),
                Paragraph(str(v)[:200], s_body),
            ])
        meta_table = Table(meta_rows, colWidths=[50*mm, 120*mm])
        meta_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F0F0F0")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE_COLOR, colors.HexColor("#FAFAFA")]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDDDDD")),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ]))
        story.append(Spacer(1, 4))
        story.append(meta_table)

    # ── Footer ────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=0.5, color=GRAY_COLOR))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        f"CATERYA Agentic Enterprise v1.0  ·  © 2026 Caterya Tech  ·  "
        f"aryhharyanto@proton.me  ·  Exported: {_now_str()}",
        s_footer
    ))

    doc.build(story)
    return buf.getvalue()


# ─── TXT Export ──────────────────────────────────────────────────────────────

def export_txt(p: ExportPayload) -> bytes:
    """Plain text export — clean, no markdown symbols."""
    lines = [
        "=" * 60,
        f"CATERYA REPORT — {p.title}",
        "=" * 60,
        f"Exported   : {_now_str()}",
        f"Agent      : {p.agent_id}",
        f"Ethics     : {p.ethics_verdict.upper()}",
        f"Duration   : {p.duration_ms:.0f}ms",
        "",
        "-" * 60,
        "TASK",
        "-" * 60,
        p.task,
        "",
        "-" * 60,
        "OUTPUT",
        "-" * 60,
        _strip_md(p.content),
        "",
    ]

    if p.steps:
        lines += ["-" * 60, "PIPELINE STEPS", "-" * 60, ""]
        for i, step in enumerate(p.steps, 1):
            lines += [
                f"Step {i}: {step.get('agent','').replace('_',' ').title()}",
                "-" * 30,
                _strip_md(step.get("output", "") or step.get("result", "")),
                "",
            ]

    if p.metadata:
        lines += ["-" * 60, "METADATA", "-" * 60]
        for k, v in p.metadata.items():
            lines.append(f"{k}: {v}")
        lines.append("")

    lines += ["=" * 60, "© 2026 Caterya Tech — aryhharyanto@proton.me", "=" * 60]
    return "\n".join(lines).encode("utf-8")


# ─── Dispatcher ──────────────────────────────────────────────────────────────

EXPORT_FORMATS = {
    "PDF (.pdf)":       ("pdf",      "application/pdf",                                              ".pdf"),
    "Excel (.xlsx)":    ("xlsx",     "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", ".xlsx"),
    "JSON (.json)":     ("json",     "application/json",                                             ".json"),
    "Markdown (.md)":   ("markdown", "text/markdown",                                                ".md"),
    "CSV (.csv)":       ("csv",      "text/csv",                                                     ".csv"),
    "Plain Text (.txt)": ("txt",     "text/plain",                                                   ".txt"),
}


def export(payload: ExportPayload, fmt: str, title: str = "") -> tuple[bytes, str, str]:
    """
    Export payload in given format.
    Returns (bytes, mime_type, filename).
    fmt: 'pdf' | 'xlsx' | 'json' | 'markdown' | 'md' | 'csv' | 'txt'
    """
    if title:
        payload.title = title

    slug = _slug(payload.title or payload.agent_id)
    ts = datetime.now().strftime("%Y%m%d_%H%M")

    # Adapt old-style dict result to ExportPayload if needed
    if isinstance(payload, dict):
        payload = ExportPayload.from_result(payload)

    # Build result dict for inner functions
    result = {
        "agent_id": payload.agent_id,
        "task": payload.task,
        "result": payload.content,
        "final_output": payload.content,
        "ethics_verdict": payload.ethics_verdict,
        "duration_ms": payload.duration_ms,
        "steps": payload.steps,
        "metadata": payload.metadata,
        "success": payload.success,
        "timestamp": payload.timestamp,
    }

    fmt = fmt.lower().replace(".", "")
    if fmt == "pdf":
        return export_pdf(result, payload.title), "application/pdf", f"caterya_{slug}_{ts}.pdf"
    elif fmt == "xlsx":
        return export_excel(result, payload.title), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", f"caterya_{slug}_{ts}.xlsx"
    elif fmt == "json":
        return export_json(result), "application/json", f"caterya_{slug}_{ts}.json"
    elif fmt in ("markdown", "md"):
        return export_markdown(result, payload.title), "text/markdown", f"caterya_{slug}_{ts}.md"
    elif fmt == "csv":
        return export_csv(result), "text/csv", f"caterya_{slug}_{ts}.csv"
    elif fmt == "txt":
        return export_txt(payload), "text/plain", f"caterya_{slug}_{ts}.txt"
    else:
        raise ValueError(f"Unknown export format: {fmt}")
